Add partial support for two internet interfaces

diff --git a/create_ap b/create_ap
--- a/create_ap
+++ b/create_ap
@@ -636,7 +636,7 @@ REDIRECT_TO_LOCALHOST=0
 
 CONFIG_OPTS=(CHANNEL GATEWAY WPA_VERSION ETC_HOSTS DHCP_DNS NO_DNS NO_DNSMASQ HIDDEN MAC_FILTER MAC_FILTER_ACCEPT ISOLATE_CLIENTS
              SHARE_METHOD IEEE80211N IEEE80211AC HT_CAPAB VHT_CAPAB DRIVER NO_VIRT COUNTRY FREQ_BAND
-             NEW_MACADDR DAEMONIZE NO_HAVEGED WIFI_IFACE INTERNET_IFACE
+             NEW_MACADDR DAEMONIZE NO_HAVEGED WIFI_IFACE INTERNET_IFACE_1 INTERNET_IFACE_2
              SSID PASSPHRASE USE_PSK)
 
 FIX_UNMANAGED=0
@@ -650,7 +650,8 @@ LOAD_CONFIG=
 CONFDIR=
 WIFI_IFACE=
 VWIFI_IFACE=
-INTERNET_IFACE=
+INTERNET_IFACE_1=
+INTERNET_IFACE_2=
 BRIDGE_IFACE=
 OLD_MACADDR=
 IP_ADDRS=
@@ -677,18 +678,32 @@ _cleanup() {
 
     rm -rf $CONFDIR
 
-    local found=0
+    local found_1=0
     for x in $(list_running_conf); do
-        if [[ -f $x/nat_internet_iface && $(cat $x/nat_internet_iface) == $INTERNET_IFACE ]]; then
-            found=1
+        if [[ -f $x/nat_internet_iface && $(cat $x/nat_internet_iface) == $INTERNET_IFACE_1 ]]; then
+            found_1=1
             break
         fi
     done
 
-    if [[ $found -eq 0 ]]; then
-        cp -f $COMMON_CONFDIR/${INTERNET_IFACE}_forwarding \
-           /proc/sys/net/ipv4/conf/$INTERNET_IFACE/forwarding
-        rm -f $COMMON_CONFDIR/${INTERNET_IFACE}_forwarding
+    if [[ $found_1 -eq 0 ]]; then
+        cp -f $COMMON_CONFDIR/${INTERNET_IFACE_1}_forwarding \
+           /proc/sys/net/ipv4/conf/$INTERNET_IFACE_1/forwarding
+        rm -f $COMMON_CONFDIR/${INTERNET_IFACE_1}_forwarding
+    fi
+
+    local found_2=0
+    for x in $(list_running_conf); do
+        if [[ -f $x/nat_internet_iface && $(cat $x/nat_internet_iface) == $INTERNET_IFACE_2 ]]; then
+            found_2=1
+            break
+        fi
+    done
+
+    if [[ $found_2 -eq 0 ]]; then
+        cp -f $COMMON_CONFDIR/${INTERNET_IFACE_2}_forwarding \
+           /proc/sys/net/ipv4/conf/$INTERNET_IFACE_2/forwarding
+        rm -f $COMMON_CONFDIR/${INTERNET_IFACE_2}_forwarding
     fi
 
     # if we are the last create_ap instance then set back the common values
@@ -719,16 +734,19 @@ _cleanup() {
         if [[ "$SHARE_METHOD" == "nat" ]]; then
             iptables -w -t nat -D POSTROUTING -s ${GATEWAY%.*}.0/24 ! -o ${WIFI_IFACE} -j MASQUERADE
             iptables -w -D FORWARD -i ${WIFI_IFACE} -s ${GATEWAY%.*}.0/24 -j ACCEPT
-            iptables -w -D FORWARD -i ${INTERNET_IFACE} -d ${GATEWAY%.*}.0/24 -j ACCEPT
+            iptables -w -D FORWARD -i ${INTERNET_IFACE_1} -d ${GATEWAY%.*}.0/24 -j ACCEPT
+            if [[ -n $INTERNET_IFACE_2 ]]; then
+                iptables -w -D FORWARD -i ${INTERNET_IFACE_2} -d ${GATEWAY%.*}.0/24 -j ACCEPT
+            fi
         elif [[ "$SHARE_METHOD" == "bridge" ]]; then
-            if ! is_bridge_interface $INTERNET_IFACE; then
+            if ! is_bridge_interface $INTERNET_IFACE_1; then
                 ip link set dev $BRIDGE_IFACE down
-                ip link set dev $INTERNET_IFACE down
-                ip link set dev $INTERNET_IFACE promisc off
-                ip link set dev $INTERNET_IFACE nomaster
+                ip link set dev $INTERNET_IFACE_1 down
+                ip link set dev $INTERNET_IFACE_1 promisc off
+                ip link set dev $INTERNET_IFACE_1 nomaster
                 ip link delete $BRIDGE_IFACE type bridge
-                ip addr flush $INTERNET_IFACE
-                ip link set dev $INTERNET_IFACE up
+                ip addr flush $INTERNET_IFACE_1
+                ip link set dev $INTERNET_IFACE_1 up
                 dealloc_iface $BRIDGE_IFACE
 
                 for x in "${IP_ADDRS[@]}"; do
@@ -736,25 +754,25 @@ _cleanup() {
                     x="${x/secondary/}"
                     x="${x/dynamic/}"
                     x=$(echo $x | sed 's/\([0-9]\)sec/\1/g')
-                    x="${x/${INTERNET_IFACE}/}"
-                    ip addr add $x dev $INTERNET_IFACE
+                    x="${x/${INTERNET_IFACE_1}/}"
+                    ip addr add $x dev $INTERNET_IFACE_1
                 done
 
-                ip route flush dev $INTERNET_IFACE
+                ip route flush dev $INTERNET_IFACE_1
 
                 for x in "${ROUTE_ADDRS[@]}"; do
                     [[ -z "$x" ]] && continue
                     [[ "$x" == default* ]] && continue
-                    ip route add $x dev $INTERNET_IFACE
+                    ip route add $x dev $INTERNET_IFACE_1
                 done
 
                 for x in "${ROUTE_ADDRS[@]}"; do
                     [[ -z "$x" ]] && continue
                     [[ "$x" != default* ]] && continue
-                    ip route add $x dev $INTERNET_IFACE
+                    ip route add $x dev $INTERNET_IFACE_1
                 done
 
-                networkmanager_rm_unmanaged_if_needed $INTERNET_IFACE
+                networkmanager_rm_unmanaged_if_needed $INTERNET_IFACE_1
             fi
         fi
     fi
@@ -971,7 +989,7 @@ write_config() {
         SSID="$2"
         PASSPHRASE="$3"
     else
-        INTERNET_IFACE="$2"
+        INTERNET_IFACE_1="$2"
         SSID="$3"
         PASSPHRASE="$4"
     fi
@@ -1219,7 +1237,7 @@ done
 if [[ -n "$LOAD_CONFIG" && $# -eq 0 ]]; then
     i=0
     # set arguments in order
-    for x in WIFI_IFACE INTERNET_IFACE SSID PASSPHRASE; do
+    for x in WIFI_IFACE INTERNET_IFACE_1 SSID PASSPHRASE; do
         if eval "[[ -n \"\$${x}\" ]]"; then
             eval "set -- \"\${@:1:$i}\" \"\$${x}\""
             ((i++))
@@ -1385,7 +1403,7 @@ if [[ $# -gt $MIN_REQUIRED_ARGS ]]; then
             usage >&2
             exit 1
         fi
-        INTERNET_IFACE="$2"
+        INTERNET_IFACE_1="$2"
         SSID="$3"
         PASSPHRASE="$4"
     else
@@ -1402,7 +1420,7 @@ else
             usage >&2
             exit 1
         fi
-        INTERNET_IFACE="$2"
+        INTERNET_IFACE_1="$2"
     fi
     if tty -s; then
         while :; do
@@ -1443,8 +1461,8 @@ else
     fi
 fi
 
-if [[ "$SHARE_METHOD" != "none" ]] && ! is_interface $INTERNET_IFACE; then
-    echo "ERROR: '${INTERNET_IFACE}' is not an interface" >&2
+if [[ "$SHARE_METHOD" != "none" ]] && ! is_interface $INTERNET_IFACE_1; then
+    echo "ERROR: '${INTERNET_IFACE_1}' is not an interface" >&2
     exit 1
 fi
 
@@ -1471,7 +1489,7 @@ if [[ $(get_adapter_kernel_module ${WIFI_IFACE}) =~ ^rtl[0-9].*$ ]]; then
     echo "WARN: If AP doesn't work, please read: howto/realtek.md" >&2
 fi
 
-if [[ $NO_VIRT -eq 1 && "$WIFI_IFACE" == "$INTERNET_IFACE" ]]; then
+if [[ $NO_VIRT -eq 1 && "$WIFI_IFACE" == "$INTERNET_IFACE_1" ]]; then
     echo -n "ERROR: You can not share your connection from the same" >&2
     echo " interface if you are using --no-virt option." >&2
     exit 1
@@ -1493,9 +1511,14 @@ COMMON_CONFDIR=/tmp/create_ap.common.conf
 mkdir -p $COMMON_CONFDIR
 
 if [[ "$SHARE_METHOD" == "nat" ]]; then
-    echo $INTERNET_IFACE > $CONFDIR/nat_internet_iface
-    cp -n /proc/sys/net/ipv4/conf/$INTERNET_IFACE/forwarding \
-       $COMMON_CONFDIR/${INTERNET_IFACE}_forwarding
+    echo $INTERNET_IFACE_1 > $CONFDIR/nat_internet_iface
+    cp -n /proc/sys/net/ipv4/conf/$INTERNET_IFACE_1/forwarding \
+       $COMMON_CONFDIR/${INTERNET_IFACE_1}_forwarding
+    if [[ -n $INTERNET_IFACE_2 ]]; then
+        echo $INTERNET_IFACE_2 > $CONFDIR/nat_internet_iface
+        cp -n /proc/sys/net/ipv4/conf/$INTERNET_IFACE_2/forwarding \
+        $COMMON_CONFDIR/${INTERNET_IFACE_2}_forwarding
+    fi
 fi
 cp -n /proc/sys/net/ipv4/ip_forward $COMMON_CONFDIR
 if [[ -e /proc/sys/net/bridge/bridge-nf-call-iptables ]]; then
@@ -1504,8 +1527,8 @@ fi
 mutex_unlock
 
 if [[ "$SHARE_METHOD" == "bridge" ]]; then
-    if is_bridge_interface $INTERNET_IFACE; then
-        BRIDGE_IFACE=$INTERNET_IFACE
+    if is_bridge_interface $INTERNET_IFACE_1; then
+        BRIDGE_IFACE=$INTERNET_IFACE_1
     else
         BRIDGE_IFACE=$(alloc_new_iface br)
     fi
@@ -1683,7 +1706,7 @@ dhcp-range=${GATEWAY%.*}.1,${GATEWAY%.*}.254,255.255.255.0,24h
 dhcp-option-force=option:router,${GATEWAY}
 dhcp-option-force=option:dns-server,${DHCP_DNS}
 EOF
-    MTU=$(get_mtu $INTERNET_IFACE)
+    MTU=$(get_mtu $INTERNET_IFACE_1)
     [[ -n "$MTU" ]] && echo "dhcp-option-force=option:mtu,${MTU}" >> $CONFDIR/dnsmasq.conf
     [[ $ETC_HOSTS -eq 0 ]] && echo no-hosts >> $CONFDIR/dnsmasq.conf
     [[ -n "$ADDN_HOSTS" ]] && echo "addn-hosts=${ADDN_HOSTS}" >> $CONFDIR/dnsmasq.conf
@@ -1717,8 +1740,14 @@ if [[ "$SHARE_METHOD" != "none" ]]; then
     if [[ "$SHARE_METHOD" == "nat" ]]; then
         iptables -w -t nat -I POSTROUTING -s ${GATEWAY%.*}.0/24 ! -o ${WIFI_IFACE} -j MASQUERADE || die
         iptables -w -I FORWARD -i ${WIFI_IFACE} -s ${GATEWAY%.*}.0/24 -j ACCEPT || die
-        iptables -w -I FORWARD -i ${INTERNET_IFACE} -d ${GATEWAY%.*}.0/24 -j ACCEPT || die
-        echo 1 > /proc/sys/net/ipv4/conf/$INTERNET_IFACE/forwarding || die
+        iptables -w -I FORWARD -i ${INTERNET_IFACE_1} -d ${GATEWAY%.*}.0/24 -j ACCEPT || die
+        if [[ -n $INTERNET_IFACE_2 ]]; then
+            iptables -w -I FORWARD -i ${INTERNET_IFACE_2} -d ${GATEWAY%.*}.0/24 -j ACCEPT || die
+        fi
+        echo 1 > /proc/sys/net/ipv4/conf/$INTERNET_IFACE_1/forwarding || die
+        if [[ -n $INTERNET_IFACE_2 ]]; then
+            echo 1 > /proc/sys/net/ipv4/conf/$INTERNET_IFACE_2/forwarding || die
+        fi
         echo 1 > /proc/sys/net/ipv4/ip_forward || die
         # to enable clients to establish PPTP connections we must
         # load nf_nat_pptp module
@@ -1731,26 +1760,26 @@ if [[ "$SHARE_METHOD" != "none" ]]; then
 
         # to initialize the bridge interface correctly we need to do the following:
         #
-        # 1) save the IPs and route table of INTERNET_IFACE
-        # 2) if NetworkManager is running set INTERNET_IFACE as unmanaged
-        # 3) create BRIDGE_IFACE and attach INTERNET_IFACE to it
+        # 1) save the IPs and route table of INTERNET_IFACE_1
+        # 2) if NetworkManager is running set INTERNET_IFACE_1 as unmanaged
+        # 3) create BRIDGE_IFACE and attach INTERNET_IFACE_1 to it
         # 4) set the previously saved IPs and route table to BRIDGE_IFACE
         #
         # we need the above because BRIDGE_IFACE is the master interface from now on
         # and it must know where is connected, otherwise connection is lost.
-        if ! is_bridge_interface $INTERNET_IFACE; then
+        if ! is_bridge_interface $INTERNET_IFACE_1; then
             echo -n "Create a bridge interface... "
             OLD_IFS="$IFS"
             IFS=$'\n'
 
-            IP_ADDRS=( $(ip addr show $INTERNET_IFACE | grep -A 1 -E 'inet[[:blank:]]' | paste - -) )
-            ROUTE_ADDRS=( $(ip route show dev $INTERNET_IFACE) )
+            IP_ADDRS=( $(ip addr show $INTERNET_IFACE_1 | grep -A 1 -E 'inet[[:blank:]]' | paste - -) )
+            ROUTE_ADDRS=( $(ip route show dev $INTERNET_IFACE_1) )
 
             IFS="$OLD_IFS"
 
             if networkmanager_is_running; then
-                networkmanager_add_unmanaged $INTERNET_IFACE
-                networkmanager_wait_until_unmanaged $INTERNET_IFACE
+                networkmanager_add_unmanaged $INTERNET_IFACE_1
+                networkmanager_wait_until_unmanaged $INTERNET_IFACE_1
             fi
 
             # create bridge interface
@@ -1760,22 +1789,22 @@ if [[ "$SHARE_METHOD" != "none" ]]; then
             echo 0 > /sys/class/net/$BRIDGE_IFACE/bridge/forward_delay
 
             # attach internet interface to bridge interface
-            ip link set dev $INTERNET_IFACE promisc on || die
-            ip link set dev $INTERNET_IFACE up || die
-            ip link set dev $INTERNET_IFACE master $BRIDGE_IFACE || die
+            ip link set dev $INTERNET_IFACE_1 promisc on || die
+            ip link set dev $INTERNET_IFACE_1 up || die
+            ip link set dev $INTERNET_IFACE_1 master $BRIDGE_IFACE || die
 
-            ip addr flush $INTERNET_IFACE
+            ip addr flush $INTERNET_IFACE_1
             for x in "${IP_ADDRS[@]}"; do
                 x="${x/inet/}"
                 x="${x/secondary/}"
                 x="${x/dynamic/}"
                 x=$(echo $x | sed 's/\([0-9]\)sec/\1/g')
-                x="${x/${INTERNET_IFACE}/}"
+                x="${x/${INTERNET_IFACE_1}/}"
                 ip addr add $x dev $BRIDGE_IFACE || die
             done
 
             # remove any existing entries that were added from 'ip addr add'
-            ip route flush dev $INTERNET_IFACE
+            ip route flush dev $INTERNET_IFACE_1
             ip route flush dev $BRIDGE_IFACE
 
             # we must first add the entries that specify the subnets and then the
